[package]
name = "api_dylib"
version = "0.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2021"

[dependencies]
api = { path = "../api" }
common = { path = "../common" }

jni = "0.21"
serde_json = "1.0"

[lib]
crate_type = ["cdylib"]
